# Generated by Django 4.2.1 on 2023-07-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_dob'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(related_name='modules', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.student'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'module')},
        ),
    ]
